---
title: "eds212-08084A"
author: "Kimmy Wong"
format: html
editor_options: 
  chunk_output_type: console
---

## Create matrices in R

```{r}
# create sequence of values ----
my_values<-seq(1,10,1)
my_values

# convert to matrix
my_matrix<-matrix(data=my_values,
                  nrow=2,
                  ncol=5,
                  byrow=TRUE)

class(my_matrix)
```

## Incorrectly declared matrix sizes

```{r}
matrix(my_values, nrow = 2, ncol = 3, byrow = TRUE)
# cuts off

matrix(my_values, nrow = 3, ncol = 4, byrow = TRUE)
# wraps and repeats numbers
```

## Math w/ matrices

```{r}
# scalar multiplication ----
4 * my_matrix

# create 2nd matrix ----
my_values2 <- seq(21, 30, 1)
my_matrix2 <- matrix(my_values2, 2, byrow = TRUE)

# matrix addition ----
my_matrix + my_matrix2

# matrix subtraction ----
my_matrix2 - my_matrix
```

```{r}
# make 2 more matrices ----
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = TRUE)

#take dot product ----
cats%*%dogs
```

## Leslie Matrix
```{r}
# create matrix ----
insect_Leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, .08, 0), nrow = 3, byrow = TRUE)

# specify initial condition (12,000 eggs, 700 larvae, 500 female adults) ----

insect_y0 <- c(12000,700,500)

# pop at year 1 ----
insect_y1 <- insect_Leslie %*% insect_y0

# pop at year 2 ---- 
insect_y2 <- insect_Leslie %*% insect_y1 

# pop at year 3 ----
insect_y3 <- insect_Leslie %*% insect_y2

# pop at year 4 ----
insect_y4 <- insect_Leslie %*% insect_y3
```

# Tree leslie example

```{r}
# make matrix ----
tree_leslie <- matrix(data = c(0,0,5000,0.1,0,0,0,.06,.95), nrow = 3, byrow = TRUE)

# initial conditions ----
tree_0 <- c(5000,0,0)

tree_1 <- tree_leslie %*% tree_0

tree_2 <- tree_leslie %*% tree_1

```


